### ISSUE TITLE
support Laravel8？

### ISSUE THREAD

**Issue by kwen8** [cidosx/laravel-redis-lock#3]
I am using Laravel 8.14.0

when install laravel-redis-lock

 Problem 1
    - ginnerpeace/laravel-redis-lock v2.3.0 requires illuminate/redis ^5.1 -> found illuminate/redis[v5.1.1, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - ginnerpeace/laravel-redis-lock v2.3.1 requires illuminate/redis ^5.1|^6.0|^7.0 -> found illuminate/redis[v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires ginnerpeace/laravel-redis-lock ~2.3 -> satisfiable by ginnerpeace/laravel-redis-lock[v2.3.0, v2.3.1].

**Comment by jay-youngn** [comment]
Test passed. Supported since `2.3.2`
